#! /bin/sh

systemctl --user set-environment WLR_DRM_DEVICES=$(realpath /dev/dri/by-path/pci-0000:00:02.0-card)

# first import environment variables from the login manager
systemctl --user import-environment
# then start the service
exec systemctl --wait --user start sway.service
